### ISSUE TITLE
ERROR: Container not found

### ISSUE THREAD

**Issue by Minituff** [Minituff/nautical-backup#203]
The issue here seems to be the `reload()` function is called on a missing container?

Will need to investigate further. Opening this ticket to track the issue.

```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/482fd217066fb628ba61e595c85ea6e45f9ae097553c5d35cce51792d584c505/json
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/backup.py", line 560, in <module>
    nautical.backup()
  File "/app/backup.py", line 494, in backup
    stop_result = self._stop_container(c)  # Stop containers
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backup.py", line 227, in _stop_container
    c.reload()  # Refresh the status for this container
    ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/models/resource.py", line 47, in reload
    new_model = self.collection.get(self.id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/models/containers.py", line 951, in get
    resp = self.client.api.inspect_container(container_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/api/container.py", line 792, in inspect_container
    return self._result(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 271, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.11/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/482fd217066fb628ba61e595c85ea6e45f9ae097553c5d35cce51792d584c505/json: Not Found ("No such container: 482fd217066fb628ba61e595c85ea6e45f9ae097553c5d35cce51792d584c505")

```

**Comment by Minituff** [comment]
Looking at my own Docker stack, it appears I was running WatchTower at the same exact time as Nautical. I am thinking that this caused a container to be updated/restarted and resulted in a different container ID which is why Nautical was unable to find it..
