### ISSUE TITLE
Bug/Feature Request: CRON Error/Disable

### ISSUE THREAD

**Issue by Riewest** [Minituff/nautical-backup#210]
The CRON `0 0 31 2 *` is a cron that will never execute since Febuary 31st doesn't exist.  When using this the Dashboard/next_cron api calls return 500 internal server error and the nautical logs throw an error about failed to find next date.

I was attempting to disable the CRON trigger and only use the api to start backups. But I ran into the above error. It doesn't crash fully so that is good. 

Feature Request: Disable CRON Trigger via env var or leave unset? guess I didn't try that

Logs:
```bash
nautical-backup  | ERROR:    Exception in ASGI application
nautical-backup  | Traceback (most recent call last):
nautical-backup  |   File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
nautical-backup  |     result = await app(  # type: ignore[func-returns-value]
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
nautical-backup  |     return await self.app(scope, receive, send)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
nautical-backup  |     await super().__call__(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
nautical-backup  |     await self.middleware_stack(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
nautical-backup  |     await self.app(scope, receive, _send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
nautical-backup  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
nautical-backup  |     await app(scope, receive, sender)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
nautical-backup  |     await self.middleware_stack(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
nautical-backup  |     await route.handle(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
nautical-backup  |     await self.app(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
nautical-backup  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
nautical-backup  |     await app(scope, receive, sender)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
nautical-backup  |     response = await func(request)
nautical-backup  |                ^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
nautical-backup  |     raw_response = await run_endpoint_function(
nautical-backup  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
nautical-backup  |     return await run_in_threadpool(dependant.call, **values)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
nautical-backup  |     return await anyio.to_thread.run_sync(func, *args)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
nautical-backup  |     return await get_async_backend().run_sync_in_worker_thread(
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
nautical-backup  |     return await future
nautical-backup  |            ^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
nautical-backup  |     result = context.run(func, *args)
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/app/api/nautical_router.py", line 48, in next_cron
nautical-backup  |     d = next_cron_occurrences(occurrences)
nautical-backup  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/app/api/utils.py", line 30, in next_cron_occurrences
nautical-backup  |     next_occurrence: datetime = cron.get_next(datetime)
nautical-backup  |                                 ^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 201, in get_next
nautical-backup  |     return self._get_next(ret_type or self._ret_type, is_prev=False)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 289, in _get_next
nautical-backup  |     result = self._calc(self.cur, expanded,
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 566, in _calc
nautical-backup  |     raise CroniterBadDateError("failed to find next date")
nautical-backup  | croniter.croniter.CroniterBadDateError: failed to find next date
nautical-backup  | ERROR:    Exception in ASGI application
nautical-backup  | Traceback (most recent call last):
nautical-backup  |   File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
nautical-backup  |     result = await app(  # type: ignore[func-returns-value]
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
nautical-backup  |     return await self.app(scope, receive, send)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
nautical-backup  |     await super().__call__(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
nautical-backup  |     await self.middleware_stack(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
nautical-backup  |     await self.app(scope, receive, _send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
nautical-backup  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
nautical-backup  |     await app(scope, receive, sender)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
nautical-backup  |     await self.middleware_stack(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
nautical-backup  |     await route.handle(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
nautical-backup  |     await self.app(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
nautical-backup  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
nautical-backup  |     raise exc
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
nautical-backup  |     await app(scope, receive, sender)
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
nautical-backup  |     response = await func(request)
nautical-backup  |                ^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
nautical-backup  |     raw_response = await run_endpoint_function(
nautical-backup  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
nautical-backup  |     return await run_in_threadpool(dependant.call, **values)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
nautical-backup  |     return await anyio.to_thread.run_sync(func, *args)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
nautical-backup  |     return await get_async_backend().run_sync_in_worker_thread(
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
nautical-backup  |     return await future
nautical-backup  |            ^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
nautical-backup  |     result = context.run(func, *args)
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/app/api/nautical_router.py", line 24, in dashboard
nautical-backup  |     next_crons = next_cron_occurrences(5)
nautical-backup  |                  ^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/app/api/utils.py", line 30, in next_cron_occurrences
nautical-backup  |     next_occurrence: datetime = cron.get_next(datetime)
nautical-backup  |                                 ^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 201, in get_next
nautical-backup  |     return self._get_next(ret_type or self._ret_type, is_prev=False)
nautical-backup  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 289, in _get_next
nautical-backup  |     result = self._calc(self.cur, expanded,
nautical-backup  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautical-backup  |   File "/usr/lib/python3.11/site-packages/croniter/croniter.py", line 566, in _calc
nautical-backup  |     raise CroniterBadDateError("failed to find next date")
nautical-backup  | croniter.croniter.CroniterBadDateError: failed to find next date
```

**Comment by Minituff** [comment]
I see, so you would like to disable CRON entirely and rely solely on the API for backups?

**Comment by Riewest** [comment]
Yea I think it would be nice for people who want to control the schedule via some external process (In my case I'll trigger it via gitlab pipeline which will give me a nice UI to check logs and make sure things are being backed up) 

It doesn't really matter to me if its a DISABLE_CRON flag or if I have to set the above cron schedule

**Comment by Minituff** [comment]
Totally understand. That's an easy addition for me to make 😁.

**Comment by Minituff** [comment]
Hey, I added this feature in the latest release: https://github.com/Minituff/nautical-backup/releases/tag/v2.3.0 !
